# Generated by Django 3.1.3 on 2022-05-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0003_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploadedFile',
            field=models.ImageField(null=True, upload_to='Uploaded/'),
        ),
    ]
